spring:
  application:
    name: config-default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fech-registry: true
    register-with-eureka: true
    service-url:
      defualtZone: http://localhost:8761/eureka
